---
version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - $PWD/config:/config
      - $PWD/data:/data
    ports:
      - 80:80
    restart: unless-stopped

